spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/emp_db
    driverClassName: org.postgresql.Driver
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
server:
  port: '9090'
